---
- name: Add containers to host inventory and disable connectivity
  hosts: all
  gather_facts: false
  vars:
    ansible_host: 192.168.122.32
    containers:
      - sensor

  tasks:
    - name: Add containers to host inventory
      add_host:
        name: "{{ item }}"
        ansible_connection: docker
        ansible_docker_extra_args: "-H=tcp://{{ ansible_host }}"
      loop: "{{ containers }}"

    - name: Disable connectivity on the sensor container
      delegate_to: sensor
      vars:
        ansible_user: root
      shell: |
        bv-cfg <<EOF
        set system.management.data.updates.portal.updates_url ''
        stage
        deploy
        EOF
      register: stdout
      changed_when: false

