- name: "Playbook to restore inventories on AAP controller"
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: Export inventory
    ansible.controller.export:
      inventory: 'C1'
      controller_host: "aap24c2.shadowman.com"
      controller_oauthtoken: "6gWPcSBjwzGN5PLGGDa9W4N29vgHT5"
    register: inventory_export

  - name: debug
    debug:
      var: inventory_export

  - name: Convert inventory vars to nice json
    ansible.builtin.set_fact:
      updated_inventory_export: "{{ inventory_export | to_nice_json }}"
      
  - name: Import inventories 
    ansible.controller.import:
      controller_oauthtoken: "6gWPcSBjwzGN5PLGGDa9W4N29vgHT5"
      controller_host: "aap24c2.shadowman.com"
      validate_certs: false
      assets: "{{ updated_inventory_export | to_nice_json | from_json() | json_query('assets') }}"
