- name: "Playbook to show wrong behaviour of createtokenr"
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Create a new token using username/password
    ansible.controller.token:
      description: 'Temporary token for subsequent tasks'
      scope: "write"
      state: present
        aap_username: "{{ api_username }}"
        aap_password: "{{ api_password }}"
        aap_hostname: "{{ tower_host | default('http://127.0.0.1') }}"
        validate_certs: false

  - name: List running jobs for the test_playbook.yml playbook
    ansible.controller.job_list:
      status: successful
      query: {"playbook": "1234.yml"}
      controller_oauthtoken: "{{ controller_token }}"
      controller_host: "{{ tower_host | default('https://10.0.79.82/') }}"
      validate_certs: false
    register: testing_jobs

  - name: Print the job info
    ansible.builtin.debug:
      var: testing_jobs
